### ISSUE TITLE
Invalid parameter when trying to add Applet

### ISSUE THREAD

**Issue by yalamber** [machinefi/w3bstream#237]
I tried to upload log.wasm file from https://github.com/machinefi/w3bstream/blob/main/_examples/log/log.wasm
I am unable to add it and below is response from server.
```
{
    "key": "badRequest",
    "code": 400000000,
    "msg": "invalid parameters",
    "desc": "",
    "canBeTalk": false,
    "id": "",
    "sources": [
        "srv-applet-mgr@0.0.1"
    ],
    "fields": [
        {
            "field": "info.wasmName",
            "msg": "missing required field",
            "in": "body"
        }
    ]
}
```

**Comment by jrynkiew** [comment]
I managed to reproduce the issue. When trying to upload a "hello world" example from the documentation with the code 

```
// log.go
package main

import (
	"unsafe"
)

// main is required for TinyGo to compile to Wasm.
func main() {}

func _log(logLevel uint32, strPtr uint32, strSize uint32)

func _start(rid uint32) int32 {
  	ptr, size := stringToPtr("Hello World!")
  	const LOG_LEVEL_INFO = 3
  	_log(LOG_LEVEL_INFO, ptr, size)
  	return 0
}

func stringToPtr(s string) (uint32, uint32) {
	buf := []byte(s)
	ptr := &buf[0]
	unsafePtr := uintptr(unsafe.Pointer(ptr))
	return uint32(unsafePtr), uint32(len(buf))
}
```

and compiling it with ```tinygo build -o log.wasm -scheduler=none --no-debug -target=wasi log.go```

When I modify the docker-compose to get around the CORS issue (to be able to log in - without this modification, the w3bstream studio will fail to log in due to CORS issue) by adding 

```
w3bstream-studio:
    image: ${WS_STUDIO_IMAGE:-ghcr.io/machinefi/w3bstream-studio:stable}
    links: 
      - "w3bapp:localhost"
    .....
```

to the w3bstream-studio definition, I can log in, but when attempting to upload the file I get this error:
![image](https://user-images.githubusercontent.com/63042547/205698693-7162c038-3ec9-434d-9a79-cfb9d6d5ed81.png)

from the w3bstream docker logs:

```{
   "@agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0",
   "@cst":5,
   "@lv":"warning",
   "@mtd":"POS",
   "@prj":"srv-applet-mgr",
   "@rmt":"192.168.80.1",
   "@status":400,
   "@tag":"access",
   "@ts":"20221205-170124.627Z",
   "@url":"/srv-applet-mgr/v0/applet/9011896374453256",
   "msg":"{\"key\":\"badRequest\",\"code\":400000000,\"msg\":\"invalid parameters\",\"desc\":\"\",\"canBeTalk\":false,\"id\":\"\",\"sources\":[\"srv-applet-mgr@0.0.1\"],\"fields\":[{\"field\":\"info.wasmName\",\"msg\":\"missing required field\",\"in\":\"body\"}]}\n"
}```

**Comment by simonerom** [comment]
What version of W3bstream are you using? i.e., did you run the official docker image with 
```
curl https://w3bstream.com/dc  > docker-compose.yaml && docker-compose up -d
```

or are you building from the latest commit?

**Comment by jrynkiew** [comment]
@simonerom The w3bstream docker-compose doesn't work properly in regards to networking. Without modifying the source of the docker-compose.yaml to edit the following line:

`NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://w3bapp:8888}`

to be 

`NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8888}`

You cannot even log into the portal. It's due to CORS issues

![image](https://user-images.githubusercontent.com/63042547/205702213-166b7dab-30ec-40b5-a1d6-a6f5c6836961.png)

I tried the link you gave, plus the instructions on the github repo, as well as the instructions on the official documentation. None of them work. They all have the same issue.

If you make the changes to `localhost` you can log in, but importing the wasm file fails also, might be due to CORS issue as well, I don't know

**Comment by yalamber** [comment]
Hello @simonerom @jrynkiew,
It's official docker image, What I did was just add below env variable in .env file and ran docker-compose up -d
NEXT_PUBLIC_API_URL=http://server_ip_address:8888

it was not running properly without this env variable as it was sending request form w3bstream studio to http://w3bapp:8888 by default

**Comment by jrynkiew** [comment]
"w3bapp" should be resolved to the container's IP address using docker-compose default networking, but it's most likely failing due to CORS issues - the w3bstream-studio container is trying to make a call to an "external" URL, and default internet security settings by default block "cross-origin" calls. The individual containers, even though they are on one host machine, refer to each other by their domain names, which is interpreted by the browser as being an external source of data, and is blocked. The w3bstream studio must refer to other container endpoints using the host mapped ports, or it will fail. Or the networking cors strict policy rules must be modified

**Comment by jrynkiew** [comment]
@yalamber @simonerom There is a workaround this issue. Please don't use the main master branch when building the w3bstream modules.

do this instead:

```
git clone https://github.com/machinefi/w3bstream.git
cd w3bstream
git checkout tags/v0.9.4
make init_submodules
make build_docker_images
make run_docker
```

Now when you go to http://localhost:3000/ you should be able to log in and upload your wasm file

Best Regards,
IoTeX team
