### ISSUE TITLE
Support SSL 

### ISSUE THREAD

**Issue by CoderZhi** [machinefi/w3bstream#257]
configure the mosquitto MQTT broker to use TLS security

**Comment by simonerom** [comment]
Let me provide more context here:

The request is from a third-party MQTT service provider and we are exploring the possibility to integrate W3bstream with their service. They support "modules" to integrate with other services, so the idea would be for them to have a W3bstream connector module in their "store" so that their users could also use W3bstream. 

Their MQTT service runs on port 8883 and requires a username and a password to subscribe.

In the W3bstream docker-compose.yaml  I only see these settings related to MQTT
```
 SRV_APPLET_MGR__BROKER__Server: mqtt://mqtt_server:1883
```
I need to set the endpoint to 
```
1d9a0d29a39445ccb6f128a39fc20115.s2.eu.hivemq.cloud:8883
```

and also set username and password in order for W3bstream to subscribe to it. So my questions are: 
1. does w3bstream support subscribing to a secure mqtt broker requiring username and password?
2. where to set MQTT credentials?
3. btw, do we/will we support MQTT on websoket?
